name: Deploy lifecycle-manager
description: Deploys lifecycle-manager.
inputs:
  klm_version_tag:
    description: The version tag for the KLM image. For example, PR-123.
    required: true
  klm_image_repo:
    description: The repository for the KLM image. For example, dev.
    required: true
runs:
  using: composite
  steps:
    - name: Deploy LM local testing kustomize
      working-directory: lifecycle-manager
      shell: bash
      run: |
        maxRetry=5
        for retry in $(seq 1 $maxRetry)
        do
          if make local-deploy-with-watcher IMG=europe-docker.pkg.dev/kyma-project/${{ inputs.klm_image_repo }}/lifecycle-manager:${{ inputs.klm_version_tag }}; then
            kubectl describe deploy/klm-controller-manager -n kcp-system
            kubectl logs deploy/klm-controller-manager -n kcp-system
            kubectl wait pods -n kcp-system -l app.kubernetes.io/name=lifecycle-manager --for condition=Ready --timeout=90s
            echo "KLM deployed successfully"
            exit 0
          elif [[ $retry -lt $maxRetry ]]; then
            echo "TEST"
            kubectl describe deploy/klm-controller-manager -n kcp-system
            kubectl logs deploy/klm-controller-manager -n kcp-system
            echo "Deploy encountered some error, will retry after 20 seconds"
            sleep 20
          else
            echo "KLM deployment failed"
            kubectl describe deploy/klm-controller-manager -n kcp-system
            kubectl logs deploy/klm-controller-manager -n kcp-system
            exit 1
          fi
        done
