apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- metrics_service.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: controller
  newName: k3d-myregistry.localhost:5000/lifecycle-manager
  newTag: "20241002110125"
